<select class="form-select" autocomplete="country" id="country_of_origin" name="country_of_origin" required>
    <option>select country</option>
    <option value="Afghanistan">Afganistan</option>
    <option value="Åland Islands">Kepulauan Aland</option>
    <option value="Albania">Albania</option>
    <option value="Algeria">Aljazair</option>
    <option value="American Samoa">Samoa Amerika</option>
    <option value="Andorra">Andorra</option>
    <option value="Angola">Angola</option>
    <option value="Anguilla">Anguilla</option>
    <option value="Antarctica">Antarktika</option>
    <option value="Antigua and Barbuda">Antigua dan Barbuda</option>
    <option value="Argentina">Argentina</option>
    <option value="Armenia">Armenia</option>
    <option value="Aruba">Aruba</option>
    <option value="Australia">Australia</option>
    <option value="Austria">Austria</option>
    <option value="Azerbaijan">Azerbaijan</option>
    <option value="Bahamas">Bahama</option>
    <option value="Bahrain">Bahrain</option>
    <option value="Bangladesh">Bangladesh</option>
    <option value="Barbados">Barbados</option>
    <option value="Belarus">Belarus</option>
    <option value="Belgium">Belgia</option>
    <option value="Belize">Belize</option>
    <option value="Benin">Benin</option>
    <option value="Bermuda">Bermuda</option>
    <option value="Bhutan">Bhutan</option>
    <option value="Bolivia (Plurinational State of)">Bolivia</option>
    <option value="Bosnia and Herzegovina">Bosnia dan Herzegovina</option>
    <option value="Botswana">Botswana</option>
    <option value="Bouvet Island">Pulau Bouvet</option>
    <option value="Brazil">Brasil</option>
    <option value="British Indian Ocean Territory">Wilayah Inggris di Samudra Hindia</option>
    <option value="Brunei Darussalam">Brunei</option>
    <option value="Bulgaria">Bulgaria</option>
    <option value="Burkina Faso">Burkina Faso</option>
    <option value="Burundi">Burundi</option>
    <option value="Cabo Verde">Tanjung Verde</option>
    <option value="Cambodia">Kamboja</option>
    <option value="Cameroon">Kamerun</option>
    <option value="Canada">Kanada</option>
    <option value="Caribbean Netherlands">Belanda Karibia</option>
    <option value="Cayman Islands">Kepulauan Cayman</option>
    <option value="Central African Republic">Republik Afrika Tengah</option>
    <option value="Chad">Chad</option>
    <option value="Chile">Cile</option>
    <option value="China">Tiongkok</option>
    <option value="Christmas Island">Pulau Natal</option>
    <option value="Cocos (Keeling) Islands">Kepulauan Cocos (Keeling)</option>
    <option value="Colombia">Kolombia</option>
    <option value="Comoros">Komoro</option>
    <option value="Congo">Kongo - Brazzaville</option>
    <option value="Congo, Democratic Republic of the">Kongo - Kinshasa</option>
    <option value="Cook Islands">Kepulauan Cook</option>
    <option value="Costa Rica">Kosta Rika</option>
    <option value="Croatia">Kroasia</option>
    <option value="Cuba">Kuba</option>
    <option value="Curaçao">Curaçao</option>
    <option value="Cyprus">Siprus</option>
    <option value="Czech Republic">Ceko</option>
    <option value="Côte d'Ivoire">Côte d’Ivoire</option>
    <option value="Denmark">Denmark</option>
    <option value="Djibouti">Jibuti</option>
    <option value="Dominica">Dominika</option>
    <option value="Dominican Republic">Republik Dominika</option>
    <option value="Ecuador">Ekuador</option>
    <option value="Egypt">Mesir</option>
    <option value="El Salvador">El Salvador</option>
    <option value="Equatorial Guinea">Guinea Ekuatorial</option>
    <option value="Eritrea">Eritrea</option>
    <option value="Estonia">Estonia</option>
    <option value="Eswatini (Swaziland)">eSwatini</option>
    <option value="Ethiopia">Etiopia</option>
    <option value="Falkland Islands (Malvinas)">Kepulauan Falkland</option>
    <option value="Faroe Islands">Kepulauan Faroe</option>
    <option value="Fiji">Fiji</option>
    <option value="Finland">Finlandia</option>
    <option value="France">Prancis</option>
    <option value="French Guiana">Guyana Prancis</option>
    <option value="French Polynesia">Polinesia Prancis</option>
    <option value="French Southern Territories">Wilayah Selatan Prancis</option>
    <option value="Gabon">Gabon</option>
    <option value="Gambia">Gambia</option>
    <option value="Georgia">Georgia</option>
    <option value="Germany">Jerman</option>
    <option value="Ghana">Ghana</option>
    <option value="Gibraltar">Gibraltar</option>
    <option value="Greece">Yunani</option>
    <option value="Greenland">Greenland</option>
    <option value="Grenada">Grenada</option>
    <option value="Guadeloupe">Guadeloupe</option>
    <option value="Guam">Guam</option>
    <option value="Guatemala">Guatemala</option>
    <option value="Guernsey">Guernsey</option>
    <option value="Guinea">Guinea</option>
    <option value="Guinea-Bissau">Guinea-Bissau</option>
    <option value="Guyana">Guyana</option>
    <option value="Haiti">Haiti</option>
    <option value="Heard Island and Mcdonald Islands">Pulau Heard dan Kepulauan McDonald</option>
    <option value="Honduras">Honduras</option>
    <option value="Hong Kong">Hong Kong DAK Tiongkok</option>
    <option value="Hungary">Hungaria</option>
    <option value="Iceland">Islandia</option>
    <option value="India">India</option>
    <option value="Indonesia">Indonesia</option>
    <option value="Iran">Iran</option>
    <option value="Iraq">Irak</option>
    <option value="Ireland">Irlandia</option>
    <option value="Isle of Man">Pulau Man</option>
    <option value="Israel">Israel</option>
    <option value="Italy">Italia</option>
    <option value="Jamaica">Jamaika</option>
    <option value="Japan">Jepang</option>
    <option value="Jersey">Jersey</option>
    <option value="Jordan">Yordania</option>
    <option value="Kazakhstan">Kazakhstan</option>
    <option value="Kenya">Kenya</option>
    <option value="Kiribati">Kiribati</option>
    <option value="Korea, North">Korea Utara</option>
    <option value="Korea, South">Korea Selatan</option>
    <option value="Kosovo">Kosovo</option>
    <option value="Kuwait">Kuwait</option>
    <option value="Kyrgyzstan">Kirgizstan</option>
    <option value="Lao People's Democratic Republic">Laos</option>
    <option value="Latvia">Latvia</option>
    <option value="Lebanon">Lebanon</option>
    <option value="Lesotho">Lesotho</option>
    <option value="Liberia">Liberia</option>
    <option value="Libya">Libya</option>
    <option value="Liechtenstein">Liechtenstein</option>
    <option value="Lithuania">Lituania</option>
    <option value="Luxembourg">Luksemburg</option>
    <option value="Macao">Makau DAK Tiongkok</option>
    <option value="Macedonia North">Makedonia Utara</option>
    <option value="Madagascar">Madagaskar</option>
    <option value="Malawi">Malawi</option>
    <option value="Malaysia">Malaysia</option>
    <option value="Maldives">Maladewa</option>
    <option value="Mali">Mali</option>
    <option value="Malta">Malta</option>
    <option value="Marshall Islands">Kepulauan Marshall</option>
    <option value="Martinique">Martinik</option>
    <option value="Mauritania">Mauritania</option>
    <option value="Mauritius">Mauritius</option>
    <option value="Mayotte">Mayotte</option>
    <option value="Mexico">Meksiko</option>
    <option value="Micronesia">Mikronesia</option>
    <option value="Moldova">Moldova</option>
    <option value="Monaco">Monako</option>
    <option value="Mongolia">Mongolia</option>
    <option value="Montenegro">Montenegro</option>
    <option value="Montserrat">Montserrat</option>
    <option value="Morocco">Maroko</option>
    <option value="Mozambique">Mozambik</option>
    <option value="Myanmar (Burma)">Myanmar (Burma)</option>
    <option value="Namibia">Namibia</option>
    <option value="Nauru">Nauru</option>
    <option value="Nepal">Nepal</option>
    <option value="Netherlands">Belanda</option>
    <option value="Netherlands Antilles">Curaçao</option>
    <option value="New Caledonia">Kaledonia Baru</option>
    <option value="New Zealand">Selandia Baru</option>
    <option value="Nicaragua">Nikaragua</option>
    <option value="Niger">Niger</option>
    <option value="Nigeria">Nigeria</option>
    <option value="Niue">Niue</option>
    <option value="Norfolk Island">Kepulauan Norfolk</option>
    <option value="Northern Mariana Islands">Kepulauan Mariana Utara</option>
    <option value="Norway">Norwegia</option>
    <option value="Oman">Oman</option>
    <option value="Pakistan">Pakistan</option>
    <option value="Palau">Palau</option>
    <option value="Palestine">Wilayah Palestina</option>
    <option value="Panama">Panama</option>
    <option value="Papua New Guinea">Papua Nugini</option>
    <option value="Paraguay">Paraguay</option>
    <option value="Peru">Peru</option>
    <option value="Philippines">Filipina</option>
    <option value="Pitcairn Islands">Kepulauan Pitcairn</option>
    <option value="Poland">Polandia</option>
    <option value="Portugal">Portugal</option>
    <option value="Puerto Rico">Puerto Riko</option>
    <option value="Qatar">Qatar</option>
    <option value="Reunion">Réunion</option>
    <option value="Romania">Rumania</option>
    <option value="Russian Federation">Rusia</option>
    <option value="Rwanda">Rwanda</option>
    <option value="Saint Barthelemy">Saint Barthélemy</option>
    <option value="Saint Helena">Saint Helena</option>
    <option value="Saint Kitts and Nevis">Saint Kitts dan Nevis</option>
    <option value="Saint Lucia">Saint Lucia</option>
    <option value="Saint Martin">Saint Martin</option>
    <option value="Saint Pierre and Miquelon">Saint Pierre dan Miquelon</option>
    <option value="Saint Vincent and the Grenadines">Saint Vincent dan Grenadine</option>
    <option value="Samoa">Samoa</option>
    <option value="San Marino">San Marino</option>
    <option value="Sao Tome and Principe">Sao Tome dan Principe</option>
    <option value="Saudi Arabia">Arab Saudi</option>
    <option value="Senegal">Senegal</option>
    <option value="Serbia">Serbia</option>
    <option value="Serbia and Montenegro">Serbia</option>
    <option value="Seychelles">Seychelles</option>
    <option value="Sierra Leone">Sierra Leone</option>
    <option value="Singapore">Singapura</option>
    <option value="Sint Maarten">Sint Maarten</option>
    <option value="Slovakia">Slovakia</option>
    <option value="Slovenia">Slovenia</option>
    <option value="Solomon Islands">Kepulauan Solomon</option>
    <option value="Somalia">Somalia</option>
    <option value="South Africa">Afrika Selatan</option>
    <option value="South Georgia and the South Sandwich Islands">Georgia Selatan & Kep. Sandwich Selatan</option>
    <option value="South Sudan">Sudan Selatan</option>
    <option value="Spain">Spanyol</option>
    <option value="Sri Lanka">Sri Lanka</option>
    <option value="Sudan">Sudan</option>
    <option value="Suriname">Suriname</option>
    <option value="Svalbard and Jan Mayen">Kepulauan Svalbard dan Jan Mayen</option>
    <option value="Sweden">Swedia</option>
    <option value="Switzerland">Swiss</option>
    <option value="Syria">Suriah</option>
    <option value="Taiwan">Taiwan</option>
    <option value="Tajikistan">Tajikistan</option>
    <option value="Tanzania">Tanzania</option>
    <option value="Thailand">Thailand</option>
    <option value="Timor-Leste">Timor Leste</option>
    <option value="Togo">Togo</option>
    <option value="Tokelau">Tokelau</option>
    <option value="Tonga">Tonga</option>
    <option value="Trinidad and Tobago">Trinidad dan Tobago</option>
    <option value="Tunisia">Tunisia</option>
    <option value="Turkey (Türkiye)">Turki</option>
    <option value="Turkmenistan">Turkmenistan</option>
    <option value="Turks and Caicos Islands">Kepulauan Turks dan Caicos</option>
    <option value="Tuvalu">Tuvalu</option>
    <option value="U.S. Outlying Islands">Kepulauan Terluar AS</option>
    <option value="Uganda">Uganda</option>
    <option value="Ukraine">Ukraina</option>
    <option value="United Arab Emirates">Uni Emirat Arab</option>
    <option value="United Kingdom">Inggris Raya</option>
    <option value="United States">Amerika Serikat</option>
    <option value="Uruguay">Uruguay</option>
    <option value="Uzbekistan">Uzbekistan</option>
    <option value="Vanuatu">Vanuatu</option>
    <option value="Vatican City Holy See">Vatikan</option>
    <option value="Venezuela">Venezuela</option>
    <option value="Vietnam">Vietnam</option>
    <option value="Virgin Islands, British">Kepulauan Virgin Britania Raya</option>
    <option value="Virgin Islands, U.S">Kepulauan Virgin Amerika Serikat</option>
    <option value="Wallis and Futuna">Kepulauan Wallis dan Futuna</option>
    <option value="Western Sahara">Sahara Barat</option>
    <option value="Yemen">Yaman</option>
    <option value="Zambia">Zambia</option>
    <option value="Zimbabwe">Zimbabwe</option>
</select>

<script>
    document.querySelectorAll('#country_of_origin option').forEach(option => {
        const value = option.value;
        const userVal = '{{$p->country_of_origin}}';
        if (String(value) === userVal) option.selected = true;
    });
</script>